### ISSUE TITLE
看到大佬增加了爱快q3000的适配，想问下如何编写dtb

### ISSUE THREAD

**Issue by andyfanybo** [seer300/openwrt-mt7621-native#1]
首先同款CPU已经有支持，我能获取到官方固件，使用binwalk提取但没发现相关文件，有路由器root权限。
大佬能不能给个教程，功德无量，壮大开源事业，Q：15977651

**Comment by seer300** [comment]
没太明白你的意思。
首先dtb是不用编写的，它是由dts文件编译生成的，dts才是需要编写的文件。
其次，如果你有官方固件，是可以从固件中提取出dtb来的，然后反编译变回dts。（固件的Linux内核版本太老就不行，7981的内核是比较新的是支持的）
提取dtb你看这个项目：https://github.com/PabloCastellano/extract-dtb
最后用dtc命令变回dts： `dtc -I dtb -O dts 1.dtb  > 1.dts`

最后，我也不是什么大佬，你这称呼有点受不起

**Comment by andyfanybo** [comment]
谢谢回复，不好意思没表达清楚，首先我的设备同款配置的已经有了openwrt支持，所以我需要搞一个我这台设备的dts文件，就和你适配了爱快q3000一样（MT798X），我现在使用开源项目extract-dtb从官方固件中提取dtb，但提取了好几个，怎么确定是哪一个呢？
![image](https://github.com/seer300/openwrt-mt7621-native/assets/170060165/3b7eb129-b86c-4920-a937-ea258c874c2d)

另外大佬是对比自己厉害的人的叫法，你肯教导，就受得起。

**Comment by seer300** [comment]
同款配置openwrt有支持的话，那上面应该也有你这款的dts，你可以搜一下。

你这款是高通的，高通的固件会把同一款CPU的所有细分型号（board id）都一起打包进固件，所以解析出来确实有这么多。
你需要确定你这款设备具体是哪个型号（board id）的，类似图里AP-CPXX这种。
如果你能接串口，开机日志中会打印，或者你在系统里使用dmesg命令（日志太多会被冲掉）

**Comment by andyfanybo** [comment]
明白了，我直接查看日志，直接使用extract-dtb提取出来的dtb编译openwrt可以吗？还是一定要dts文件去编译。

**Comment by seer300** [comment]
openwrt编译必须是dts的，你用dtb反解析出的dts能直接拿去编

**Comment by andyfanybo** [comment]
京东云亚瑟已经有openwrt支持，京东云雅典娜暂时还没有，但两款设备配置很相似，但我注意到两者差别比较大，官方的dts很多采用十六进制，并且多了很多内容，后面还需要自己修改是吧，有没有相关指南可以参考，谢谢。



[亚瑟openwrt编译dts-ipq6018-jdc-ax1800-pro.dts.txt](https://github.com/user-attachments/files/15735679/openwrt.dts-ipq6018-jdc-ax1800-pro.dts.txt)
[雅典娜官方固件反编译dts-ipq6018-jdc-ax6600-pro.dts.txt](https://github.com/user-attachments/files/15735688/dts-ipq6018-jdc-ax6600-pro.dts.txt)

**Comment by seer300** [comment]
十六进制多是因为这是反编译的dts，它包含引用的公共dtsi文件，比如ax1800的：
```
#include "ipq6018.dtsi"
#include "ipq6018-512m.dtsi"
#include "ipq6018-ess.dtsi"
#include "ipq6018-nss.dtsi"
```
在上游编译它的人手里，原始dts的内容是和亚瑟的那个类似的，比较易读。
反编译dts包含了所有引用的dtsi内容，是完整的，你可以先直接用于编译。

如果你需要修改，高通官方提供的SDK里是有每个board id的原始dts的，如果你能拿到的话会方便很多。
没有的话，就只能在这个反编译的上面改，编译时原始dts的`&`引用会被编译成十六进制，但是还是能找到对应关系的。
比如你这个雅典娜：
```
leds {
	compatible = "gpio-leds";
	pinctrl-0 = <0x50>;
	pinctrl-names = "default";

	led@79 {
		label = "led_b1";
		gpios = <0x0d 0x4f 0x00>;
		linux,default-trigger = "led_b1";
		default-state = "off";
	};
```
其中`pinctrl-0 = <0x50>;`，原始应该是`<&leds_pins>`，0x50是替换后的地址。
你在文件中搜索0x50，可以找到：
```
leds_pins {
		linux,phandle = <0x50>;
		phandle = <0x50>;

		led_b1 {
			pins = "gpio79";
			function = "gpio";
			drive-strength = <0x08>;
			bias-pull-down;
		};
```
这就是上面leds引用的地方。
大概就是这样，不是太好用语言描述

**Comment by andyfanybo** [comment]
雅典娜的dts参考了亚瑟和小米AX9000（以太网芯片相同），有个问题是高通的机型都会有WiFi节点：
&wifi {
	qcom,ath11k-calibration-variant = "GL-iNet-GL-AX1800";
};
&wifi {
	status = "okay";
	qcom,ath11k-calibration-variant = "JDC-AX1800-Pro";
	qcom,ath11k-fw-memory-mode = <1>;
};
我在dts中定义了以太网交换芯片，但没有发现WiFi芯片的定义，难道这个WiFi是通用的，只要在qcom,ath11k-calibration-variant =后面加上机型，比如雅典娜我定义了JDC-ATHENA，但这个机型不需要在其它地方先定义吗，这里确实没搞懂，不知道大佬了不了解原理，谢谢。
